{% set version = "2.17.0" %}

package:
  name: libimagequant
  version: {{ version }}

source:
  url: https://github.com/ImageOptim/libimagequant/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9f6cc50182be4d2ece75118aa0b0fd3e9bbad06e94fd6b9eb3a4c08129c2dd26

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('libimagequant', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - cmake        # [win]
    - llvm-openmp  # [not linux]
    - libgomp      # [linux]

test:
  commands:
    # shared
    - test -f $PREFIX/lib/libimagequant.so              # [linux]
    - test -f $PREFIX/lib/libimagequant.dylib           # [osx]
    - if not exist %LIBRARY_BIN%\imagequant.dll exit 1  # [win]

    # absence of static libraries
    - test ! -f $PREFIX/lib/libimagequant.a             # [not win]

    # header
    - test -f $PREFIX/include/libimagequant.h || (echo "libimagequant.h not found" && exit 1)  # [unix]
    - if not exist %LIBRARY_INC%\libimagequant.h exit 1                                        # [win]

about:
  home: https://pngquant.org/lib/
  license: GPL-3.0-or-later
  license_file: COPYRIGHT
  summary: Palette quantization library that powers pngquant and other PNG optimizers
  dev_url: https://github.com/ImageOptim/libimagequant

extra:
  recipe-maintainers:
    - izahn
    - h-vetinari
