{% set name = "libimagequant" %}
{% set version = "2.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ImageOptim/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 11b15f4057feb9de724415f71a8e369942218e1691bb75838167bc986591fc36

build:
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage('libimagequant', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libimagequant.so  # [linux]
    - test -f $PREFIX/lib/libimagequant.0.dylib  # [osx]

about:
  home: https://pngquant.org/
  license: GPL-3.0-or-later
  license_file: COPYRIGHT
  summary: Palette quantization library that powers pngquant and other PNG optimizers

extra:
  recipe-maintainers:
    - izahn
